
export const API_URL = 'http://localhost:3001/'

export const FETCH_ALL_CARS_SUCCEEDED = 'FETCH_ALL_CARS_SUCCEEDED'
export const FETCH_ALL_CARS_REQUESTED = 'FETCH_ALL_CARS_REQUESTED'
export const FETCH_ALL_CARS_FAILED = 'FETCH_ALL_CARS_FAILED'

export const FETCH_SINGLE_CAR_SUCCEEDED = 'FETCH_SINGLE_CAR_SUCCEEDED'
export const FETCH_SINGLE_CAR_REQUESTED = 'FETCH_SINGLE_CAR_REQUESTED'
export const FETCH_SINGLE_CAR_FAILED = 'FETCH_SINGLE_CAR_FAILED'

export const FETCH_ALL_COLORS_SUCCEEDED = 'FETCH_ALL_COLORS_SUCCEEDED'
export const FETCH_ALL_COLORS_REQUESTED = 'FETCH_ALL_COLORS_REQUESTED'
export const FETCH_ALL_COLORS_FAILED = 'FETCH_ALL_COLORS_FAILED'

export const FETCH_ALL_MANUFACTURERS_SUCCEEDED = 'FETCH_ALL_MANUFACTURERS_SUCCEEDED'
export const FETCH_ALL_MANUFACTURERS_REQUESTED = 'FETCH_ALL_MANUFACTURERS_REQUESTED'
export const FETCH_ALL_MANUFACTURERS_FAILED = 'FETCH_ALL_MANUFACTURERS_FAILED'

export const ALL_CARS_BY_MANUFACTURER_FETCHED = 'ALL_CARS_BY_MANUFACTURER_FETCHED'

export const ALL_CARS_BY_A_COLOR_FETCHED = 'ALL_CARS_BY_A_COLOR_FETCHED'
export const ALL_CARS_SORTED_BY_MILEAGE_IN_ASCENDING_ORDER = 'ALL_CARS_SORTED_BY_MILEAGE_IN_ASCENDING_ORDER'
export const ALL_CARS_SORTED_BY_MILEAGE_IN_DESCENDING_ORDER = 'ALL_CARS_SORTED_BY_MILEAGE_IN_DESCENDING_ORDER'
export const DETAILS_OF_SELECTED_CAR_DISPLAYED = 'DETAILS_OF_SELECTED_CAR_DISPLAYED'

export const ADD_CAR_TO_FAVORITES_COLLECTION_REQUESTED = 'ADD_CAR_TO_FAVORITES_COLLECTION_REQUESTED'
export const ADD_CAR_TO_FAVORITES_COLLECTION_SUCCEEDED = 'ADD_CAR_TO_FAVORITES_COLLECTION_SUCCEEDED'
export const ADD_CAR_TO_FAVORITES_COLLECTION_FAILED = 'ADD_CAR_TO_FAVORITES_COLLECTION_FAILED'

export const REMOVE_CAR_FROM_FAVORITES_COLLECTION_REQUESTED = 'REMOVE_CAR_FROM_FAVORITES_COLLECTION_REQUESTED'
export const REMOVE_CAR_FROM_FAVORITES_COLLECTION_SUCCEEDED = 'REMOVE_CAR_FROM_FAVORITES_COLLECTION_SUCCEEDED'
export const REMOVE_CAR_FROM_FAVORITES_COLLECTION_FAILED = 'REMOVE_CAR_FROM_FAVORITES_COLLECTION_FAILED'

export const PAGE_NUMBER_CHANGED = 'PAGE_NUMBER_CHANGED'
